apps/parser/internal/commands/commands.go
apps/parser/internal/commands/manage/add_aliase.go
apps/parser/internal/commands/manage/remove_aliase.go

Adds request by /cc @AlexWayfer

feat(parser): add chat commands for manage aliases

---

apps/dashboard/pages/commands/[[...module]].tsx

fix: horizontal scroll on commands page

---

apps/dashboard/components/layout/navbar.tsx
apps/dashboard/pages/_app.tsx
apps/dashboard/services/dashboard/useTheme.ts

resolve #284 
also fixed blinking

feat(dashboard): detect system theme

---

apps/dashboard/components/layout/navbar.tsx
apps/dashboard/public/TsuwariInCircle.svg

feat(dashboard): add logo in navbar

---

frontend/dashboard/components/confirmDelete.tsx
frontend/dashboard/components/song-requests/player/alerts.tsx
frontend/dashboard/components/song-requests/player/duration-slider.tsx
frontend/dashboard/components/song-requests/player/youtube-player.tsx
frontend/dashboard/components/song-requests/queue/queue-list.tsx
frontend/dashboard/pages/_app.tsx
frontend/dashboard/pages/song-requests/player.tsx
frontend/dashboard/styles/global.css
pnpm-lock.yaml

Add text to song request player page, which will indicate state

---

frontend/dashboard/components/appProvider.tsx
frontend/dashboard/pages/_app.tsx
frontend/dashboard/pages/song-requests/player.tsx
frontend/dashboard/services/api/profile.ts
frontend/dashboard/services/dashboard/useLocale.tsx
frontend/public/pages/_app.tsx

fix(dashboard): selected lang not working

---

frontend/dashboard/components/song-requests/helpers.ts
frontend/dashboard/components/song-requests/queue/queue-list.tsx
frontend/dashboard/styles/draggable.ts
frontend/public/pages/_app.tsx

feat(dashboard): display createdAt field in songrequests list table

---

apps/api/internal/api/v1/greetings/dto.go
apps/api/internal/api/v1/greetings/service.go

fix: nil pointer dereference

---

frontend/landing/src/components/index/Reviews.vue

chore(landing): fix valorant spelling in 7ssk7 review

---

apps/api/internal/impl_unprotected/stats/stats.go
frontend/landing/src/components/home/StatsList.astro
libs/grpc/protos/api/stats.proto

feat: used commands

---

apps/parser/internal/commands/stats/user_me.go
apps/parser/internal/variables/user/commands.go
apps/parser/internal/variables/variables.go

There is what it looks like:
danluki: 0 used emotes · 1 used commands · 0.0h watched · 1 messages · 0 used points · 0 songs requested
Code is the same as in used emotes

feat(parser): used commands variable

---

frontend/overlays/src/pages/tts.vue

fix(overlays): tts

---

frontend/dashboard/src/main.css
frontend/landing/src/styles/fonts.scss
frontend/public-page/src/style.css

fix(frontend): cyrillic fonts

---

frontend/landing/src/components/hero/hero-chat-messages.ts
frontend/landing/src/components/hero/hero-chat.vue
frontend/landing/src/components/hero/hero.astro
frontend/landing/src/components/hero/use-chat.ts

feat(landing): pause chat scroll on landing on mouse hover

---

frontend/dashboard/src/pages/overlays/chat/Chat.vue

fix(dashboard): scroll of chat preview

---

frontend/dashboard/src/layout/dashboardsMenu.vue

fix(dashboard): horizontal scroll of dashboard menu

---

cli/internal/cmds/migrations/migrations.go

fix(cli): add .go migrations initialization

---

apps/parser/internal/commands/dudes/grow.go
frontend/overlays/src/composables/dudes/dudes-config.ts
frontend/overlays/src/composables/dudes/use-dudes-iframe.ts
frontend/overlays/src/composables/dudes/use-dudes-socket.ts
frontend/overlays/src/composables/dudes/use-dudes.ts
frontend/overlays/src/pages/overlays/dudes.vue
libs/bus-core/websockets/dudes.go
libs/types/src/overlays.ts

fix(overlays): request dudes user settings

---

frontend/dashboard/package.json
frontend/dashboard/src/api/admin/badges.ts
frontend/dashboard/src/api/admin/notifications.ts
frontend/dashboard/src/composables/use-mutation.ts
frontend/dashboard/src/features/admin-panel/manage-badges/components/badges-list.vue
frontend/dashboard/src/features/admin-panel/manage-badges/composables/use-badges-actions.ts
frontend/dashboard/src/plugins/urql.ts
pnpm-lock.yaml

https://commerce.nearform.com/open-source/urql/docs/basics/document-caching/

refactor(dashboard): do not use normalized cache

---

frontend/dashboard/src/pages/user-settings/user-public-settings.vue

fix(dashboard): word limit for channel description

---

.gitignore
apps/api-gql/internal/gql/resolvers/keywords.resolver.go
apps/api-gql/schema/keywords.graphqls
frontend/dashboard/src/api/keywords.ts
frontend/dashboard/src/components/keywords/modal.vue
frontend/dashboard/src/components/keywords/types.ts
frontend/dashboard/src/pages/Keywords.vue
package.json
pnpm-lock.yaml

feat(dashboard): keywords gql

---

frontend/dashboard/src/api/greetings.ts
frontend/dashboard/src/components/greetings/modal.vue
frontend/dashboard/src/components/greetings/types.ts
frontend/dashboard/src/locales/en.json
frontend/dashboard/src/pages/Greetings.vue

feat(dashboard): greetings gql

---

frontend/dashboard/src/features/chat-alerts/ui/settings.vue
frontend/dashboard/src/pages/chat-alerts.vue

refactor(dashboard): update chat alerts ui

---

bun.lock
docker-compose.dev.yml
frontend/dashboard/package.json
frontend/dashboard/src/features/community-chat-messages/ui/chat-messages.vue
web/app/app.vue

Video: 
https://fileditchfiles.me/file.php?f=/s22/XaLmgSDbYiwQbrQrgnN.mp4

feat: add chat-like scroll behaviour to chat logs 

---

frontend/dashboard/src/features/overlays/valorant-stats/builder.vue
frontend/dashboard/src/features/overlays/valorant-stats/composables/use-valorant-stats.ts
libs/frontend-valorant-stats/src/types.ts
libs/frontend-valorant-stats/src/widget.vue
web/layers/overlays/pages/o/[apiKey]/valorant-stats.client.vue

Исправил отображение шрифта Inter на странице оверлея. На винде вместо него отображается Arial 
Есть ещё баг. Если у человека не привязана учётка Valorant, тогда на странице оверлея отображается кнопка "Connect". По какой-то причине она не работает.  Предполагаю, что проблема в функции login в valorant-stats/builder.vue.
async function login() {
if (authLink.value) return
window.open(authLink.value, 'Twir connect integration', 'width=800,height=600')
}
"!" забыл перед authLink.value
Но я не могу проверить прав я или нет. У меня проект не хочет запускаться для разработки. Мне стало лень разбираться почему и я не пытался снова

chore(overlays): add inter font in overlay page
